---
title: "R Notebook"
output: html_notebook
---

# Preliminaries 

```{r echo=TRUE}
library(ggplot2) 
library(tidyverse) 
library(lme4) 
library(stringr)
library(languageR)
library(lmerTest)
library(reshape2)
library(grid)

source("helpers.R")

bran_palette = c("#7ae7e5", "#fe5f55", "#B2A6DE", "#14342b", "#69385c")

theme_set(theme_minimal())
```

# Word Reading Item

```{r}
spr_data <- read.csv('sprt_data.csv') %>%
  filter(trial_id!= 'example')

spr_exclusion <- spr_data %>% group_by(workerid) %>%
  summarise(accuracy = mean(response_correct)) %>%
  mutate(exclude = ifelse(accuracy < 0.85,'Yes','No')) %>% 
  filter(exclude == 'Yes')

spr_data <- spr_data[!(spr_data$workerid %in% spr_exclusion$workerid),]
```

```{r}
spr_data <- spr_data %>%
  group_by(trial_id) %>%
  mutate(id_mean = mean(log(rt))) %>%
  mutate(exclusion = (log(rt) < mean(log(rt)) - 2*sd(log(rt))|(log(rt) > mean(log(rt)) + 2*sd(log(rt))))) %>%
  ungroup() %>%
  filter(exclusion==FALSE)
```

```{r}
spr_data <- spr_data %>%
  filter(!is.na(subject_information.age)) %>%
  filter(!is.na(subject_information.party_alignment))
```

```{r}
spr_data <- spr_data %>%
  mutate(trial_congruency = ifelse(condition=='congruent_male' | condition == 'congruent_female','congruent','neutral')) %>%
  mutate(trial_gender = ifelse(condition=='neutral_female' | condition == 'congruent_female','female','male')) %>%
  mutate(morph_type = ifelse(lexeme!= 'actor' & lexeme!= 'host' & lexeme !='hunter' & lexeme!= 'villain' & lexeme!= 'heir' & lexeme!= 'hero','compound','adoption'))
```

```{r}
spr_data <- spr_data %>%
  mutate(form_length = str_length(form))

spr_residual_model <- lm(log(rt)~form_length, data = spr_data)

spr_data <- spr_data %>%
  mutate(resid_rt = resid(spr_residual_model))
```

```{r}
spr_data %>%
  group_by(trial_gender,trial_congruency,word_idx,morph_type) %>%
  summarise(MeanRT = mean(resid_rt), CI.Low = ci.low(resid_rt), CI.High = ci.high(resid_rt)) %>%
  mutate(YMin = MeanRT - CI.Low, YMax = MeanRT + CI.High) %>%
  ggplot(aes(x=word_idx,y=MeanRT,linetype=trial_congruency,color=trial_gender)) + 
  geom_point() + 
  geom_line() + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax), width=.25) + 
  facet_wrap(~morph_type)
```

```{r}
spr_data %>%
  group_by(trial_gender,trial_congruency,word_idx,morph_type) %>%
  summarise(MeanRT = mean(rt), CI.Low = ci.low(rt), CI.High = ci.high(rt)) %>%
  mutate(YMin = MeanRT - CI.Low, YMax = MeanRT + CI.High) %>%
  ggplot(aes(x=word_idx,y=MeanRT,linetype=trial_congruency,color=trial_gender)) + 
  geom_point() + 
  geom_line() + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax), width=.25) + 
  facet_wrap(~morph_type)
```
