---
title: "Production Only"
output: html_notebook
---

```{r}
library(tidyverse)
library(lme4)
library(ggpubr)

source("helpers.R")
```

```{r}
bran_palette = c("#7ae7e5","#B2A6DE", "#fe5f55", "#14342b", "#69385c")

theme_set(theme_minimal())
```

```{r}
lex_freqs <- read.csv("freq_preped.csv") %>%
  mutate(left_surprisal = (-log(mean_left_neutral))/(-log(mean_left_gendered))) %>%
  mutate(right_surprisal = (-log(mean_right_neutral))/(-log(mean_right_gendered)))
```

```{r}
gender_transcendence_cols <- c('subject_information.gender_q1','subject_information.gender_q2','subject_information.gender_q3','subject_information.gender_q4','subject_information.gender_q5')

gender_linked_cols <- c('subject_information.gender_q6','subject_information.gender_q7','subject_information.gender_q8','subject_information.gender_q9','subject_information.gender_q10','subject_information.gender_q11','subject_information.gender_q12','subject_information.gender_q13')
```

## Production Task Study

### Methods

### Analysis

**Data Read-in**

```{r}
prod_data <- read.csv("production_data.csv")
```

**Exclusions**

```{r}
prod_exclusion <- prod_data %>% filter(name=='attention') %>%
  group_by(workerid) %>%
  summarise(accuracy = mean(correct)) %>%
  mutate(exclude = ifelse(accuracy < 0.80,'Yes','No')) %>%
  filter(exclude == "Yes")
```

```{r}
prod_data <- prod_data[!(prod_data$workerid %in% prod_exclusion$workerid),]
```

**Additional Information** 

```{r}
prod_data <- prod_data %>%
  mutate(gender_trans = 100 - (rowMeans(prod_data[gender_transcendence_cols]))) %>%
  mutate(gender_link = rowMeans(prod_data[gender_linked_cols])) 

gender_all = c('gender_trans','gender_link')

prod_data <- prod_data %>%
  mutate(gender_total = rowMeans(prod_data[gender_all]))
``` 

```{r}
prod_data <- prod_data %>%
  filter(type == "critical") %>%
  mutate(response_gender = ifelse(response == "actress" | response == "anchorwoman" | response == "stewardess" | response == "businesswoman" | response == 'camerawoman' | response == 'congresswoman' | response == 'craftswoman' | response == 'crewwoman' | response == 'firewoman' | response == 'forewoman'  | response == 'heiress' | response == 'heroine' | response == 'hostess' | response == 'huntress' | response == 'laywoman' | response == 'policewoman' | response == 'saleswoman' | response == 'stuntwoman' | response == 'villainess' | response == 'weatherwoman',"female",ifelse(response == "anchor" | response == "flight attendant" | response == "businessperson" | response == 'camera operator' | response == 'congressperson' | response == 'craftsperson' | response == 'crewmember' | response == 'firefighter' | response == 'foreperson' | response == 'layperson' | response == 'police officer' | response == 'salesperson' | response == 'stunt double' | response == 'meteorologist',"neutral",ifelse(response == "anchorman" | response == "steward" | response == "businessman" | response == 'cameraman' | response == 'congressman' | response == 'craftsman' | response == 'crewman' | response == 'fireman' | response == 'foreman' | response == 'layman' | response == 'policeman' | response == 'salesman' | response == 'stuntman' | response == 'weatherman',"male",'male/neutral')))) %>%
  mutate(congruency = ifelse(gender == response_gender,"true","false")) %>%
  mutate(neutrality = ifelse(response_gender == "neutral","true","false"))%>%
  mutate(morph_type = ifelse(lexeme!= 'actor' & lexeme!= 'host' & lexeme !='hunter' & lexeme!= 'villain' & lexeme!= 'heir' & lexeme!= 'hero','compound','adoption')) %>%
  mutate(poli_party = ifelse(subject_information.party_alignment == 1 | subject_information.party_alignment == 2,'Republican',ifelse(subject_information.party_alignment == 4 | subject_information.party_alignment == 5,'Democrat','Non-Partisan')))
```

**Responses by Political Ideology**

```{r}
prod_data %>% 
  filter(!is.na(poli_party)) %>%
  filter(morph_type =="compound") %>%
  ggplot(aes(x=poli_party, fill=response_gender)) + 
  geom_bar(position="fill") + 
  facet_wrap(~gender) + 
  scale_fill_manual(values = bran_palette) + 
  labs(x="Participant Political Party", fill="Gender of Response", y="Proportion of Responses", title="Gender of Response by Gender of Stimulus Name") + 
  theme(text=element_text(size=15)) + 
  theme(axis.text.x = element_text(angle=25))
```

```{r}
ggsave("prod_all_poli.png", width=7,height=5,path='/Users/branpap/Desktop/gender_processing/talks_and_papers/qp_paper/figures')
``` 




```{r}
prod_data %>% 
  filter(!is.na(subject_information.party_alignment)) %>%
  filter(morph_type =="compound") %>%
  ggplot(aes(x=subject_information.party_alignment, fill=response_gender)) + 
  geom_bar(position="fill") + 
  facet_wrap(~gender) + 
  scale_fill_manual(values = bran_palette) + 
  labs(x="Participant Political Party", fill="Gender of Response", y="Proportion of Responses", title="Gender of Response by Gender of Stimulus Name")
```

**Gender of Response by Political Alignment and Gender Ideology**

```{r}
prod_data %>%
  filter(!is.na(poli_party)) %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="" & morph_type=="compound") %>%
  group_by(gender,gender_total,poli_party) %>%
  summarise(proportion = mean(response_neutral)) %>%
  ggplot(aes(x=gender_total, y=proportion, color=gender)) +
    geom_point() + 
    geom_smooth() + 
    scale_color_manual(values = bran_palette) +
    facet_wrap(~poli_party) + 
    labs(x="Gender Ideology Score", y="Proportion of Gender Neutral Responses",color="Gender of Name Seen") + 
    theme(text=element_text(size=15))
```

```{r}
ggsave("prod_neutral_poli.png", width=10,height=5,path='/Users/branpap/Desktop/gender_processing/talks_and_papers/qp_paper/figures')
``` 

```{r}
prod_data %>%
  filter(!is.na(poli_party)) %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  group_by(gender,subject_information.age,poli_party) %>%
  summarise(proportion = mean(response_neutral)) %>%
  ggplot(aes(x=subject_information.age, y=proportion, color=gender)) +
    geom_point() + 
    geom_smooth() + 
    scale_color_manual(values = bran_palette) 
```
```{r}
my_comparisons <- list( c("Democrat","Republican"),c("Democrat","Non-Partisan"),c("Republican","Non-Partisan"))
```


```{r}
prod_data %>%
  filter(!is.na(poli_party)) %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  filter(subject_information.gender == "Male" | subject_information.gender == "Female") %>%
  filter(poli_party != "Non-Partisan") %>%
  group_by(gender,workerid,poli_party,subject_information.gender) %>%
  summarise(proportion = mean(response_neutral)) %>%
  ggplot(aes(x=poli_party, y=proportion, fill=poli_party)) +
  geom_boxplot(varwidth = T) + 
  geom_jitter(alpha=0.1) + 
  scale_fill_manual(values=bran_palette) + 
  facet_grid(subject_information.gender~gender) + 
  theme(legend.position = "none") + 
  labs(x="Participant Political Party", y="Proportion",title="Mean Prop. of Neutral Responses by Stimuli Gender") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=20)) + 
  stat_compare_means(label = "p.signif")
```

```{r}
prod_data %>%
  filter(!is.na(poli_party)) %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  group_by(gender,workerid,poli_party,subject_information.gender) %>%
  summarise(proportion = mean(response_neutral)) %>%
  ggplot(aes(x=poli_party, y=proportion, fill=poli_party)) +
  geom_boxplot(varwidth = T) + 
  geom_jitter(alpha=0.1) + 
  scale_fill_manual(values=bran_palette) + 
  facet_wrap(~gender) + 
  theme(legend.position = "none") + 
  labs(x="Participant Political Party", y="Proportion",title="Mean Prop. of Neutral Responses by Stimuli Gender") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=20)) 
#%+ #  stat_compare_means(comparisons = my_comparisons, label = "p.signif")
```

```{r}
ggsave("prod_neutral_poli_box.png", width=7, height=5,path='/Users/branpap/Desktop/gender_processing/talks_and_papers/qp_paper/figures')
``` 

```{r}
prod_data %>%
  filter(!is.na(poli_party)) %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  group_by(gender,poli_party) %>%
  summarise(proportion = mean(response_neutral)) %>%
  ggplot(aes(x=poli_party, y=proportion, fill=poli_party)) +
  geom_bar(stat="identity") + 
  scale_fill_manual(values=bran_palette) + 
  facet_wrap(~gender) + 
  theme(legend.position = "none") + 
  labs(x="Participant Political Party", y="Proportion",title="Mean Prop. of Neutral Responses by Stimuli Gender") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=20)) 
```



```{r}
gender_comparisons <- list( c("male","female"))
```

```{r}
prod_data %>%
  filter(!is.na(poli_party)) %>%
  filter(poli_party != "Non-Partisan") %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  group_by(gender,workerid,poli_party,subject_information.gender) %>%
  summarise(proportion = mean(response_neutral)) %>%
  ggplot(aes(x=gender, y=proportion, fill=gender)) +
  geom_boxplot(varwidth = T) + 
  geom_jitter(alpha=0.1) + 
  scale_fill_manual(values=bran_palette) + 
  facet_wrap(~poli_party) + 
  theme(legend.position = "none") + 
  labs(x="Stimuli Gender", y="Proportion",title="Mean Prop. of Neutral Responses by Stimuli Gender") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=20)) 
```
```{r}
ggsave("prod_neutral_poli_box_gender.png", width=7, height=5,path='/Users/branpap/Desktop/gender_processing/talks_and_papers/qp_paper/figures')
``` 

```{r}
prod_data %>%
  filter(!is.na(poli_party)) %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  group_by(subject_information.gender,workerid,poli_party) %>%
  summarise(proportion = mean(response_neutral)) %>%
  ggplot(aes(x=poli_party, y=proportion, fill=poli_party)) +
  geom_boxplot(varwidth = T) + 
  geom_jitter(alpha=0.1) + 
  scale_fill_manual(values=bran_palette) + 
  facet_wrap(~subject_information.gender) + 
  theme(legend.position = "none") + 
  labs(x="Participant Political Party", y="Proportion",title="Mean Prop. of Neutral Responses by Stimuli Gender") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=20)) + 
  stat_compare_means(comparisons = my_comparisons, label = "p.signif")
```


```{r}
prod_data %>%
  filter(poli_party == "Democrat" | poli_party =="Republican") %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender=="male") %>%
  group_by(workerid,poli_party) %>%
  summarise(proportion = mean(response_neutral)) %>%
  ggplot(aes(x=poli_party, y=proportion, fill=poli_party)) +
  geom_boxplot(varwidth = T) + 
  geom_jitter(alpha=0.1) + 
  scale_fill_manual(values=bran_palette) + 
  theme(legend.position = "none") + 
  labs(x="Participant Political Party", y="Proportion",title="Mean Prop. of Neutral Responses by Stimuli Gender") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=20)) + 
  stat_compare_means()
```
```{r}
prod_data %>%
  filter(poli_party == "Democrat" | poli_party =="Republican") %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender=="female") %>%
  group_by(workerid,poli_party) %>%
  summarise(proportion = mean(response_neutral)) %>%
  ggplot(aes(x=poli_party, y=proportion, fill=poli_party)) +
  geom_boxplot(varwidth = T) + 
  geom_jitter(alpha=0.1) + 
  scale_fill_manual(values=bran_palette) + 
  theme(legend.position = "none") + 
  labs(x="Participant Political Party", y="Proportion",title="Mean Prop. of Neutral Responses by Stimuli Gender") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=20)) + 
  stat_compare_means()
```
**Gender by Gender, no Ideology**

```{r}
prod_data %>%
  filter(morph_type =="compound") %>%
  ggplot(aes(x=gender, fill=response_gender)) + 
  geom_bar(position="fill") + 
  scale_fill_manual(values = bran_palette) + 
  labs(x="Stimulus Gender", fill="Gender of Response", y="Proportion of Responses", title="Gender of Response by Gender of Stimulus Name") +
  theme_minimal()
```

**Models**

```{r}
prod_data_compounds <- prod_data %>%
  filter(morph_type == "compound") %>%
  mutate(cgender_total = scale(gender_total)) %>%
  mutate(response_congruency = as.numeric(ifelse(congruency=="true","1","0"))) %>%
  mutate(cage = scale(subject_information.age)) %>%
  mutate(neutrality_binary = ifelse(neutrality=="true",1,0))
```

```{r}
final_dat <- merge(prod_data_compounds,lex_freqs,by="lexeme") %>%
  mutate(neutrality_binary = ifelse(neutrality=="true",1,0)) %>%
  filter(morph_type == "compound") %>%
  mutate(cgender_total = scale(gender_total)) %>%
  mutate(response_congruency = as.numeric(ifelse(congruency=="true","1","0"))) %>%
  mutate(cage = scale(subject_information.age)) %>%
  mutate(cmean_left_neutral = scale(mean_left_neutral)) %>%
  mutate(mean_all = (mean_left_neutral + mean_right_neutral)/2) %>%
  mutate(cmean_all = scale(mean_all))
```

```{r}
production_model_one <- lmer(neutrality_binary~cgender_total*poli_party + gender + cmean_all + (1|workerid) + (1|lexeme) + (1|name) + (1|cage),data=final_dat)
```

```{r}
summary(production_model_one)
```


# Some Prop Tables

```{r}
(table(prod_data$subject_information.gender))
```



```{r}
prod_gender_table <- prod_data %>%
  group_by(workerid,subject_information.gender,poli_party) %>%
  summarise(subject_gender = paste(unique(subject_information.gender)))

table(prod_gender_table$subject_gender,prod_gender_table$poli_party)
```

```{r}
prod_data_all <- read.csv("production_data.csv") %>%
  filter(type=="filler_semantic" | type=="filler_grammatical") %>%
  group_by(lexeme,type) %>%
  summarise(lexeme=paste(unique(lexeme)))
```

```{r}
table(prod_data_all$type)
```


```{r}
prod_data_means <- prod_data %>%
  filter(!is.na(poli_party)) %>%
  filter(poli_party != "Non-Partisan") %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  group_by(gender,workerid,poli_party,subject_information.gender,subject_information.age,subject_information.education,gender_total) %>%
  summarise(proportion = mean(response_neutral)) 
```

```{r}
table(prod_data_means$proportion,prod_data_means$poli_party,prod_data_means$gender)
```


```{r}
production_model_two <- lmer(proportion~poli_party*gender + (1|workerid) + (1|subject_information.age) + (1|subject_information.gender), data=prod_data_means)
```

```{r}
summary(production_model_two)
```

```{r}
prod_data_means_male <- prod_data %>%
  filter(!is.na(poli_party)) %>%
  filter(poli_party != "Non-Partisan") %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="" & gender!="female") %>%
  group_by(workerid,poli_party,subject_information.gender,subject_information.age,subject_information.education) %>%
  summarise(proportion = mean(response_neutral)) 
```

```{r}
production_model_three <- lmer(proportion~poli_party +(1|subject_information.age) + (1|subject_information.gender), data=prod_data_means_male)
```

```{r}
summary(production_model_three)
```

```{r}
prod_data_means_female <- prod_data %>%
  filter(!is.na(poli_party)) %>%
  filter(poli_party != "Non-Partisan") %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="" & gender!="male") %>%
  group_by(workerid,poli_party,subject_information.gender,subject_information.age,subject_information.education) %>%
  summarise(proportion = mean(response_neutral)) 
```

```{r}
production_model_four <- lmer(proportion~poli_party +(1|subject_information.age) + (1|subject_information.gender), data=prod_data_means_female)
```

```{r}
summary(production_model_four)
```

```{r}
prod_data_means_all <- prod_data %>%
  filter(!is.na(poli_party)) %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  group_by(gender,workerid,poli_party,subject_information.gender,subject_information.age,subject_information.education,gender_total) %>%
  summarise(proportion = mean(response_neutral)) 
```

```{r}
prod_data %>%
  filter(!is.na(poli_party)) %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  group_by(gender,workerid,poli_party,subject_information.gender) %>%
  summarise(proportion = mean(response_neutral)) %>%
  ggplot(aes(x=proportion, fill=poli_party)) +
  geom_histogram() + 
  scale_fill_manual(values=bran_palette) + 
  facet_grid(poli_party~gender) + 
  theme(legend.position = "none") + 
  labs(x="Proportion of Responses", y="Number of Participants",title="Proportions of Neutral Responses by Stimuli Gender", fill="Political Party") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=20)) +
  theme_grey()
#%+ #  stat_compare_means(comparisons = my_comparisons, label = "p.signif")
```

```{r}
prod_data %>%
  filter(!is.na(poli_party)) %>%
  filter(poli_party != "Non-Partisan") %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  filter(lexeme=="flight attendant") %>%
  group_by(gender,workerid,poli_party,subject_information.gender) %>%
  summarise(proportion = mean(response_neutral)) %>%
  ggplot(aes(x=gender, y=proportion, fill=gender)) +
  geom_boxplot(varwidth = T) + 
  geom_jitter(alpha=0.1) + 
  scale_fill_manual(values=bran_palette) + 
  facet_wrap(~poli_party) + 
  theme(legend.position = "none") + 
  labs(x="Stimuli Gender", y="Proportion",title="Mean Prop. of Neutral Responses by Stimuli Gender") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=20)) 
```




```{r}
prod_data_means_rep <- prod_data_means %>%
  filter(poli_party == "Republican")
```


```{r}
production_model_five <- lmer(proportion~gender_total + (1|subject_information.age), data=prod_data_means_rep)
```

```{r}
summary(production_model_five)
```


```{r}
prod_data_means_dem <- prod_data_means %>%
  filter(poli_party == "Democrat")
```

```{r}
production_model_five <- lmer(proportion~gender_total + (1|workerid), data=prod_data_means_dem)
```

```{r}
summary(production_model_five)
```


```{r}
prod_data %>%
  filter(!is.na(poli_party)) %>%
  filter(morph_type == "compound") %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  group_by(gender,lexeme,poli_party,subject_information.gender) %>%
  summarise(proportion = mean(response_neutral)) %>%
  ggplot(aes(x=gender, y=proportion)) +
  geom_boxplot(varwidth=T) + 
  scale_fill_manual(values=bran_palette) + 
#  facet_wrap(~lexeme) + 
  theme(legend.position = "none") + 
  labs(x="Proportion of Responses", y="Number of Participants",title="Proportions of Neutral Responses by Stimuli Gender", fill="Political Party") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=20)) +
  theme_grey() + 
  stat_compare_means()
```
```{r}
prod_data %>%
  filter(!is.na(poli_party)) %>%
  filter(lexeme == "flight attendant") %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  group_by(gender) %>%
  summarize(average_flight = mean(response_neutral)) %>%
  ggplot(aes(x=gender, y=average_flight)) +
  geom_bar(stat="identity") + 
  scale_fill_manual(values=bran_palette) + 
  theme(legend.position = "none") + 
  labs(x="Proportion of Responses", y="Number of Participants",title="Proportions of Neutral Responses by Stimuli Gender", fill="Political Party") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=20)) +
  theme_grey() + 
  stat_compare_means()
```


```{r}
prod_data %>%
  filter(!is.na(poli_party)) %>%
  #filter(poli_party != "Non-Partisan") %>%
  group_by(poli_party) %>%
  summarize(mean_ideo = mean(gender_total), CI.Low = ci.low(gender_total), CI.High = ci.high(gender_total)) %>%
  mutate(YMin = mean_ideo - CI.Low, YMax = mean_ideo + CI.High) %>%
  ggplot(aes(x=poli_party,y=mean_ideo,fill=poli_party)) + 
  geom_bar(stat='identity') + 
  #geom_point(data=prod_data, aes(x=poli_party,y=gender_total),alpha=0.15, position="jitter") + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25) + 
  theme_bw() + 
  labs(x="Participant Political Party", y="Mean Gender Ideology") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=5, vjust = .7)) + 
  scale_fill_manual(values = bran_palette) +
  theme(legend.position = "none")
```

```{r}
ggsave("prod_ideology_party.png", width=7, height=5,path='/Users/branpap/Desktop/gender_processing/talks_and_papers/qp_paper/figures')
```

```{r}
prod_data %>%
  group_by(workerid,poli_party,gender_total) %>%
  ggplot(aes(x=poli_party, y=gender_total)) + 
  geom_boxplot()
```

```{r}
final_dat_flight <- final_dat %>%
  filter(lexeme=="flight attendant")
```


```{r}
production_model_flight <- lmer(neutrality_binary~gender + (1|name), data=final_dat_flight)
```

```{r}
summary(production_model_flight)
```


```{r}
prod_data_means_all %>%
  filter(!is.na(poli_party)) %>%
  #filter(poli_party != "Non-Partisan") %>%
  group_by(gender,poli_party) %>%
  summarize(mean_prop = mean(proportion), CI.Low = ci.low(proportion), CI.High = ci.high(proportion)) %>%
  mutate(YMin = mean_prop - CI.Low, YMax = mean_prop + CI.High) %>%
  ggplot(aes(x=poli_party,y=mean_prop,fill=poli_party)) + 
  geom_bar(stat='identity') + 
  geom_point(data=prod_data_means_all, aes(x=poli_party,y=proportion),alpha=0.15, position="jitter") + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25) + 
  facet_wrap(~ gender) + 
  theme_bw() + 
  labs(x="Participant Political Party", y="Mean Proportion of Neutral Responses",title="Neutral Responses by Stimuli Gender") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=5, vjust = .7)) + 
  scale_fill_manual(values = bran_palette) +
  theme(legend.position = "none")
```
```{r}
ggsave("prod_neutral_poli_bar_gender.png", width=7, height=5,path='/Users/branpap/Desktop/gender_processing/talks_and_papers/qp_paper/figures')
```


```{r}
prod_data %>%
  filter(!is.na(poli_party)) %>%
  filter(morph_type == "compound") %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  #filter(poli_party != "Non-Partisan") %>%
  group_by(gender,poli_party) %>%
  summarize(mean_prop = mean(response_neutral), CI.Low = ci.low(response_neutral), CI.High = ci.high(response_neutral)) %>%
  mutate(YMin = mean_prop - CI.Low, YMax = mean_prop + CI.High) %>%
  ggplot(aes(x=poli_party,y=mean_prop,fill=poli_party)) + 
  geom_bar(stat='identity') + 
  geom_point(data=prod_data_means_all, aes(x=poli_party,y=proportion),alpha=0.15, position="jitter") + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25) + 
  facet_wrap(~ gender) + 
  theme_bw() + 
  labs(x="Participant Political Party", y="Mean Proportion of Neutral Responses",title="Neutral Responses by Stimuli Gender") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=5, vjust = .7)) + 
  scale_fill_manual(values = bran_palette) +
  theme(legend.position = "none")
```
```{r}
ggsave("prod_neutral_poli_bar_nonmean.png", width=7, height=5,path='/Users/branpap/Desktop/gender_processing/talks_and_papers/qp_paper/figures')
```

```{r}
prod_data_binary_party <- prod_data %>%
  filter(poli_party == "Democrat" | poli_party == "Republican") %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  filter(morph_type == "compound")
```


```{r}
prod_neutral_poli_nomean_model <- lmer(response_neutral~poli_party + gender + (1|lexeme) + (1|name) + (1|workerid),data=prod_data_binary_party)
```

```{r}
summary(prod_neutral_poli_nomean_model)
```


```{r}
prod_data %>%
  filter(!is.na(poli_party)) %>%
  filter(morph_type == "compound") %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  #filter(poli_party != "Non-Partisan") %>%
  group_by(gender,poli_party) %>%
  summarize(mean_prop = mean(response_neutral), CI.Low = ci.low(response_neutral), CI.High = ci.high(response_neutral)) %>%
  mutate(YMin = mean_prop - CI.Low, YMax = mean_prop + CI.High) %>%
  ggplot(aes(x=gender,y=mean_prop,fill=gender)) + 
  geom_bar(stat='identity') + 
  geom_point(data=prod_data_means_all, aes(x=gender,y=proportion),alpha=0.15, position="jitter") + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25) + 
  facet_wrap(~ poli_party) + 
  theme_bw() + 
  labs(x="Stimulus Gender", y="Mean Proportion of Neutral Responses",title="Neutral Responses by Stimuli Gender") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=5, vjust = .7)) + 
  scale_fill_manual(values = bran_palette) +
  theme(legend.position = "none")
```

```{r}
ggsave("prod_neutral_gender_bar_nonmean.png", width=7, height=5,path='/Users/branpap/Desktop/gender_processing/talks_and_papers/qp_paper/figures')
```

```{r}
prod_data_means_all %>%
  filter(!is.na(poli_party)) %>%
  #filter(poli_party != "Non-Partisan") %>%
  group_by(gender,poli_party) %>%
  summarize(mean_prop = mean(proportion), CI.Low = ci.low(proportion), CI.High = ci.high(proportion)) %>%
  mutate(YMin = mean_prop - CI.Low, YMax = mean_prop + CI.High) %>%
  ggplot(aes(x=gender,y=mean_prop,fill=gender)) + 
  geom_bar(stat='identity') + 
  geom_point(data=prod_data_means_all, aes(x=gender,y=proportion),alpha=0.15, position="jitter") + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25) + 
  facet_wrap(~ poli_party) + 
  theme_bw() + 
  labs(x="Gender Seen", y="Mean Proportion of Neutral Responses",title="Neutral Responses by Stimuli Gender") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=5, vjust = .7)) + 
  scale_fill_manual(values = bran_palette) +
  theme(legend.position = "none")
```
```{r}
ggsave("prod_neutral_gender_bar.png", width=7, height=5,path='/Users/branpap/Desktop/gender_processing/talks_and_papers/qp_paper/figures')
```

```{r}
prod_data %>%
  filter(!is.na(poli_party)) %>%
  filter(morph_type == "compound") %>%
  mutate(response_neutral = ifelse(response_gender == "neutral" | response_gender == "male/neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  group_by(gender,lexeme,poli_party,subject_information.gender) %>%
  summarise(proportion = mean(response_neutral)) %>%
  group_by(gender,lexeme) %>%
  summarize(mean_prop = mean(proportion), CI.Low = ci.low(proportion), CI.High = ci.high(proportion)) %>%
  mutate(YMin = mean_prop - CI.Low, YMax = mean_prop + CI.High) %>%
  ggplot(aes(x=gender,y=mean_prop,fill=gender)) + 
  geom_bar(stat='identity') + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25) + 
  facet_wrap(~lexeme) + 
  theme(legend.position = "none") + 
  labs(x="Participant Political Party", y="Mean Proportion of Gender-Neutral Responses",title="Proportions of Neutral Responses by Stimuli Gender", fill="Political Party") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=20)) +
  theme_grey() 
```

```{r}
prod_data %>%
  filter(!is.na(poli_party)) %>%
  mutate(response_neutral = ifelse(response_gender == "neutral" | response_gender == "male/neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  group_by(morph_type) %>%
  summarize(mean_prop = mean(response_neutral), CI.Low = ci.low(response_neutral), CI.High = ci.high(response_neutral)) %>%
  mutate(YMin = mean_prop - CI.Low, YMax = mean_prop + CI.High) %>%
  ggplot(aes(x=morph_type,y=mean_prop, fill=morph_type)) + 
  geom_bar(stat='identity') + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25) + 
  labs(x="Morphological Process", y="Mean Proportion of Neutral Responses") + 
  theme(text=element_text(size=16)) + 
  theme(axis.text.x = element_text(angle=5, vjust = .7)) + 
  scale_fill_manual(values = bran_palette) +
  theme(legend.position = "none")
```

```{r}
ggsave("prod_neutral_morph_bar.png", width=7, height=5,path='/Users/branpap/Desktop/gender_processing/talks_and_papers/qp_paper/figures')
```

```{r}
prod_data_means_all <- prod_data %>%
  filter(!is.na(poli_party)) %>%
  mutate(response_neutral = ifelse(response_gender == "neutral",1,0)) %>%
  filter(gender!="filler" & gender!= "attention" & gender!="") %>%
  group_by(gender,workerid,poli_party,subject_information.gender,subject_information.age,subject_information.education,gender_total) %>%
  summarise(proportion = mean(response_neutral)) 
```
