---
title: "Merge to the Berge"
output: html_notebook
---
```{r}
library(tidyverse)
```

```{r}
inauguration_2021 = c("#5445b1", "#749dae", "#f3c483", "#5c1a33", "#cd3341","#f7dc6a")
```

```{r}
maze <- read.csv("merged_all_maze.csv")
spr <- read.csv("merged_all_spr.csv") 
prod <- read.csv("merged_all_prod.csv")
```

```{r}
gender_transcendence_cols <- c('subject_information.gender_q1','subject_information.gender_q2','subject_information.gender_q3','subject_information.gender_q4','subject_information.gender_q5')

gender_linked_cols <- c('subject_information.gender_q6','subject_information.gender_q7','subject_information.gender_q8','subject_information.gender_q9','subject_information.gender_q10','subject_information.gender_q11','subject_information.gender_q12','subject_information.gender_q13')
```

```{r}
maze <- maze %>%
  mutate(gender_trans = 100 - (rowMeans(maze[gender_transcendence_cols]))) %>%
  mutate(gender_link = rowMeans(maze[gender_linked_cols])) 

gender_all = c('gender_trans','gender_link')

maze <- maze %>%
  mutate(gender_total = rowMeans(maze[gender_all])) %>%
  group_by(workerid) %>%
  summarize(gt = paste(unique(gender_total)),gender = paste(unique(subject_information.gender)),experiment="Maze") 
```

```{r}
spr <- spr %>%
  mutate(gender_trans = 100 - (rowMeans(spr[gender_transcendence_cols]))) %>%
  mutate(gender_link = rowMeans(spr[gender_linked_cols])) 

gender_all = c('gender_trans','gender_link')

spr <- spr %>%
  mutate(gender_total = rowMeans(spr[gender_all])) %>%
  group_by(workerid) %>%
  summarize(gt = paste(unique(gender_total)),gender = paste(unique(subject_information.gender)),experiment="Self-Paced Reading")
```

```{r}
prod <- prod %>%
  mutate(gender_trans = 100 - (rowMeans(prod[gender_transcendence_cols]))) %>%
  mutate(gender_link = rowMeans(prod[gender_linked_cols])) 

gender_all = c('gender_trans','gender_link')

prod <- prod %>%
  mutate(gender_total = rowMeans(prod[gender_all])) %>%
  group_by(workerid) %>%
  summarize(gt = paste(unique(gender_total)),gender = paste(unique(subject_information.gender)),experiment="Production") 
```

```{r}
test <- rbind(maze,spr) 
test <- rbind(test,prod)
```

```{r}
cons_text <- textGrob("Conservative", gp=gpar(fontsize=10, fontface="bold"))
lib_text <- textGrob("Liberal", gp=gpar(fontsize=10, fontface="bold"))
```

```{r}
test %>%
  filter(gender != "") %>%
  ggplot(aes(x=gender, y=as.numeric(gt), fill=gender)) + 
  geom_boxplot() + 
  theme_minimal() + 
  facet_wrap(~experiment) + 
  labs(x="Participant Gender", y="Gender Ideology Score") + 
  theme(legend.position = 'none') + 
  scale_fill_manual(values=inauguration_2021)
```

```{r}
ggsave(height=4,width=7,path="/Users/branpap/Desktop/gender_processing/talks_and_papers/qp_paper",filename="merge_ideo_pure.png")
```