---
title: "Gender Ideologies and Language Production: A Fill-in-the-Blank Task"
author: "B. Papineau"
date: "2021"
output:
  html_notebook:
    toc: yes
    toc_float:
      collapsed: no
    number_sections: yes
    theme: journal
  html_document:
    toc: yes
    df_print: paged
---

## Packages
For this analysis, we require the following packages:

```{r echo=TRUE}
library(ggplot2) 
library(tidyverse) 
library(lme4) 
library(stringr)
library(languageR)
library(lmerTest)
library(reshape2)
```

```{r}
theme_set(theme_minimal())
```

# Data Read-In

```{r}
all_data <- read.csv('production_pilot-merged.csv')
```


# Exclusion

```{r}
exclusion <- all_data %>% filter(name=='attention') %>%
  group_by(workerid) %>%
  summarise(accuracy = mean(correct)) %>%
  mutate(exclude = ifelse(accuracy < 0.80,'Yes','No')) 
```

all_data <- all_data[!(all_data$workerid %in% exclusion$workerid),] %>%
  filter(rt !='null')

# Gender Subscores
```{r}
gender_transcendence_cols <- c('subject_information.gender_q1','subject_information.gender_q2','subject_information.gender_q3','subject_information.gender_q4','subject_information.gender_q5')

gender_linked_cols <- c('subject_information.gender_q6','subject_information.gender_q7','subject_information.gender_q8','subject_information.gender_q9','subject_information.gender_q10','subject_information.gender_q11','subject_information.gender_q12','subject_information.gender_q13')
```

```{r}
all_data <- all_data %>%
  mutate(gender_trans = 100 - (rowMeans(all_data[gender_transcendence_cols]))) %>%
  mutate(gender_link = rowMeans(all_data[gender_linked_cols])) 

gender_all = c('gender_trans','gender_link')

all_data <- all_data %>%
  mutate(gender_total = rowMeans(all_data[gender_all]))
```

# Political Alignments

```{r}
all_data <- all_data %>%
  mutate(poli_party = ifelse(subject_information.party_alignment == 1 | subject_information.party_alignment == 2,'Republican',ifelse(subject_information.party_alignment == 4 | subject_information.party_alignment == 5,'Democrat','Non-Partisan')))
```

# Response Genders 

```{r}
crit_data <- all_data %>%
  filter(type == "critical") %>%
  mutate(response_gender = ifelse(response == "actress" | response == "anchorwoman" | response == "stewardess" | response == "businesswoman" | response == 'camerawoman' | response == 'congresswoman' | response == 'craftswoman' | response == 'crewwoman' | response == 'firewoman' | response == 'forewoman'  | response == 'heiress' | response == 'heroine' | response == 'hostess' | response == 'huntress' | response == 'laywoman' | response == 'policewoman' | response == 'saleswoman' | response == 'stuntwoman' | response == 'villainess' | response == 'weatherwoman',"female",ifelse(response == "anchor" | response == "flight attendant" | response == "businessperson" | response == 'camera operator' | response == 'congressperson' | response == 'craftsperson' | response == 'crewmember' | response == 'firefighter' | response == 'foreperson' | response == 'layperson' | response == 'police officer' | response == 'salesperson' | response == 'stunt double' | response == 'meteorologist',"neutral",ifelse(response == "anchorman" | response == "steward" | response == "businessman" | response == 'cameraman' | response == 'congressman' | response == 'craftsman' | response == 'crewman' | response == 'fireman' | response == 'foreman' | response == 'layman' | response == 'policeman' | response == 'salesman' | response == 'stuntman' | response == 'anchorman',"male",'male/neutral'))))
```

```{r}
view_crit <- crit_data %>%
  select(response,response_gender,gender)
```


# Data Visualization
Now we can start analysing the data by means of data visualization. 

```{r}
inauguration_2021 = c("#5445b1", "#749dae", "#f3c483", "#5c1a33", "#cd3341","#f7dc6a")
```

```{r}
ggplot(view_crit, aes(x=response_gender,color=gender)) + 
  geom_bar(stat="count")
```

