---
title: "Pilot Data Analysis"
author: "Bran T. Papineau"
output: html_notebook
---

```{r}
library(ggplot2)
library(tidyverse)
library(lme4)
```



```{r}
all_data <- read.csv("gender_processing_data_final.csv") %>%
  filter(trial_id!='example' & (region=='critical')) %>%
  mutate(trial_gender = ifelse(condition =='neutral_female' | condition=='congruent_female',"female","male")) %>%
  mutate(gender_transcendence = 100 - rowMeans(cbind(subject_information.gender_q1,subject_information.gender_q2,subject_information.gender_q3,subject_information.gender_q4,subject_information.gender_q5))) %>%
  mutate(morph_type = ifelse(lexeme == "actor" | lexeme =="villain" | lexeme == "heir"| lexeme == "host" | lexeme == "hunter" | lexeme == "hero","adoption","suppletion"))
```

```{r}
summary(all_data)
```

```{r}
ggplot(all_data, aes(x=condition, y=log(rt))) +
  geom_col()
```

```{r}
summary(lm(gender_transcendence~subject_information.party_alignment, data = all_data))
```


```{r}
basic_model <- lm(log(rt)~condition*log1p(gender_transcendence)*morph_type, data = all_data)
```

```{r}
summary(basic_model)
```

```{r}
plot(basic_model)
```


```{r}
all_data_model <- lmer(log(rt)~condition*morph_type*log1p(gender_transcendence) + (1|name) + (1|lexeme) + (1|trial_id) + (1|workerid), data=all_data)
```

```{r}
summary(all_data_model)
```

```{r}
ggplot(all_data, aes(log(rt))) + 
  geom_histogram()
```


```{r}
exp(-0.11159)
```

```{r}
plot(all_data_model)
```

